### ISSUE TITLE
Subscription tax percentage

### ISSUE THREAD

**Issue by mpoulsen** [peterkeen/payola#103]
It would be nice if Payola Subscriptions could have a `tax_percent` as supported by Stripe: https://stripe.com/docs/api#create_subscription

When selling software subscriptions in EU, you need to be able to apply different VAT rates depending on what country the customer is from. At the moment there is no way to do this with Payola, right?

**Comment by peterkeen** [comment]
That's super interesting! Stripe hasn't talked publicly about it at all, it just showed up in the API one day. You're right, at the moment there's no way to do this. It should probably be something along the lines of how `setup_fee` is handled now (passed into `CreateSubscription`, persisted to the db, and passed to `customer.subscriptions.create` in `StartSubscription`).

**Comment by mpoulsen** [comment]
Yes, it must be something new, they also recently added this FAQ: https://support.stripe.com/questions/handling-tax-on-subscriptions

The approach sounds right. It would be very much appreciated!

Later there could also be some cases where there will be a need to change the the `tax_percent` in a subscription, but I guess that could also be done by creating a new subscription.

**Comment by bkno** [comment]
In the API it is possible to update `tax_percent` in a subscription as well https://stripe.com/docs/api#update_subscription

This all seems pretty tough to manage, wonder if some UK people are just using $ and paying VAT on the lump sum that ends up in their bank account?

**Comment by mpoulsen** [comment]
@bkno Yes, we are talking about the tax_percent on the subscription.

Using tax_percent is very easy to do, especially compared to the alternative: Since a plan has a fixed price, the only way to have different VAT rates, is by creating a new Plan for every VAT rate, meaning that you have to have about 28 times more Stripe plans then normal.

So IMO when selling software in EU, using the tax_percent on a subscription is an absolute must. For our project, that meant that we had to stop using Payola.

**Comment by bkno** [comment]
Sorry was just confirming that tax_percent can be updated on a subscription and not just on creation (Stripe support page only mentioned creation).

I've just read up on the 2015 EU VAT requirements, a pain to say the least. Two services I've seen that handle this automatically, on top of Stripe, are [Taxamo](https://www.taxamo.com) and [Quaderno](http://quaderno.io) - not sure how workable they might be with Payola yet though.

**Comment by mpoulsen** [comment]
Yes, a pain indeed. But using a service only to figure our the VAT is not necessary (except if you can also use it as your invoice/accounting system).

When it comes to figuring out the VAT rate and validating the VAT no, I would recommend these gems:
 - https://github.com/adamcooke/json-vat
 - https://github.com/yolk/valvat
 - https://github.com/hexorx/countries (also use it for a lot of other stuff) 


If someone reading this needs inspiration to implement these:
```
class Customer < ActiveRecord::Base
  before_validation :adjust_registration_no, if: :registration_no_changed?
  validates :registration_no, valvat: {lookup: true, match_country: :country_id}, if: :require_registration_no?

  def require_registration_no?
    customer_type.company? and Country.eu?(country_id)
  end

  def apply_vat?
    (customer_type.person? and Country.eu?(country_id)) or country_id == YOUR_COUNTRY
  end

  def vat_rate
    if apply_vat?
      country.vat_rate || 0
    else
      0
    end
  end

  def adjust_registration_no
    return unless matches = registration_no.match(/^([[:alpha:]]*)([[:digit:]]*)$/i)
    code, number = matches[1..2]

    # Insert country code, if not entered.
    if code.length == 0 and number.length > 4
      self.registration_no = country_id + number

    # Convert to uppercase if in lowercase.
    elsif code.length == 2 and code != code.upcase
      self.registration_no = code.upcase + number
    end
  end
end
```

**Comment by eliotsykes** [comment]
Added in #167.
