### ISSUE TITLE
Offer a synchronous mode

### ISSUE THREAD

**Issue by tfe** [peterkeen/payola#104]
My use case is that I have a third-party hosted microsite on which I want to put a Stripe Checkout button. It would be easy enough to drop Payola into my existing Rails app to process the payment and redirect back to the microsite, but the asynchronous nature doesn't allow it (needs the payola JS running on the page to check the transaction status).

But if a wait for the user is tolerable (as in my case), it'd be nice to just do the transaction synchronously and redirect to the `redirect_url` after `create_object` rather than rendering the status as JSON.

**Comment by peterkeen** [comment]
Sorry, this isn't a use case that we're going to support. Async is at the core of Payola's customer-facing interface.
