### ISSUE TITLE
NoMethodError: undefined method `plan' for #<Payola::Subscription:0x007fc47c5a4d10>

### ISSUE THREAD

**Issue by krainboltgreene** [peterkeen/payola#105]
```
NoMethodError: undefined method `plan' for #<Payola::Subscription:0x007fc47c5a4d10>
from /Users/krainboltgreene/.rvm/gems/ruby-2.1.5@sketchymicro-app/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
```

**Comment by peterkeen** [comment]
Hi @krainboltgreene ! Thanks for the bug report, but this isn't enough to make a diagnosis. Could you please paste the complete stack trace and a snippet of the code that is causing the error?

**Comment by krainboltgreene** [comment]
That's all I get back :/

It comes down to `Payola::Subscription` having `plan_id` and `plan_type` but not `plan=` or `plan`. The stack is actually from `Payola::CreateSubscription`.

**Comment by peterkeen** [comment]
Weird. `Payola::Subscription` has a `belongs_to :plan, polymorphic: true`, right here: https://github.com/peterkeen/payola/blob/master/app/models/payola/subscription.rb#L15

**Comment by krainboltgreene** [comment]
Yeah, I'm at a complete loss. I'm not modifying that class at all.

**Comment by krainboltgreene** [comment]
Now I'm getting this:

```
undefined method `owner=' for #<Payola::Subscription:0x007fab43a2c5b0>
activemodel (4.2.0) lib/active_model/attribute_methods.rb:433:in `method_missing'
sketchy (1.4.1) lib/payola/create_subscription.rb:19:in `block in call'
activerecord (4.2.0) lib/active_record/core.rb:282:in `initialize'
activerecord (4.2.0) lib/active_record/inheritance.rb:61:in `new'
activerecord (4.2.0) lib/active_record/inheritance.rb:61:in `new'
sketchy (1.4.1) lib/payola/create_subscription.rb:7:in `call'
```

**Comment by peterkeen** [comment]
What version of Payola are you using? Latest is 1.3.0.

**Comment by krainboltgreene** [comment]
So it ended up being that if a Rails Engine defines a class that matches a gem's class name it no longer attempts the autoload from the gem.

Basically instead of adding behavior I was replacing the entire model.

**Comment by peterkeen** [comment]
Thanks for the update! I'd love to hear about what behavior you're adding. There might be a better way to add it than by extending the class.

**Comment by krainboltgreene** [comment]
Haha, no, the change was for a weird payment system for a client. Not very
useful for the project.

**Comment by boethius** [comment]
@krainboltgreene @peterkeen I know this was a while ago, but I'm trying to monkey patch metadata into the stripe requests. I'm getting the same error, regardless of including `'payola'` or not. Short of injecting the entire code base, I'm a little stuck.
