### ISSUE TITLE
Should Payola create a Sale object when a Subscription is charged?

### ISSUE THREAD

**Issue by jagthedrummer** [peterkeen/payola#108]
I recently refunded a Subscription charge to someone and ended up with an error in my exception reporter of `NoMethodError: undefined method 'refund!' for nil:NilClass`. This happened in the event subscription for `charge.refunded` that's in the default Payola initializer (`config/initializers/payola.rb`). I double checked and there are no `Payola::Sale` objects in my DB. So I'm wondering if Payola should create one of these each time that a Subscription is charged. Or maybe I should remove that event subscription? (That doesn't seem right...) Anyway, just wanted to get your thoughts on this before I went charging off on a PR.

**Comment by blainejohnson17** [comment]
They are not being created because of Issue #106. The sale is not saved because the exception is raised and the process never finishes.

**Comment by jagthedrummer** [comment]
Haha, DERP! You'd think I might have caught that since I've been looking right at that code. Man, apparently it's time to step away from the keyboard.

**Comment by jagthedrummer** [comment]
Closing this since it was just due to my inability to connect dots last night.
