### ISSUE TITLE
Multiple "One time payments" with the same card

### ISSUE THREAD

**Issue by dylanjha** [peterkeen/payola#109]
I am looking to have a situation where the following happens:
1. User pays for an item- the "One Time Payment" example works for this.
2. User can buy that item or a different item again in the future, and use the same card they used the first time.

At first glance, it appears that this is possible with a little extra work on the server side:
* Find last card the user used through the Payola::Sale objects that the user is the owner of. Get the stripe_customer_id, and find the default source for the stripe customer.
* Manually create the Payola::Sale object with this stripe customer and the customer's default source.

Questions:
1. Does Payola have some way of supporting that I want to do that I haven't discovered?
2. If not, is this a sane approach? I'm not even sure it will work, because it looks like the Payola::Sale object expects a stripe_token, which has to be supplied from the client library.

Thanks for creating this library @peterkeen it would be great if I could get a little feedback here. And furthermore, I'm happy to contribute in any way if you point me in the right direction.

**Comment by peterkeen** [comment]
There's no built-in method for this, but what you describe should work.
Actually it's even a little easier than that. You can just find the last
sale for the customer and create a new Payola::Sale with the same
`stripe_customer_id`. When you call `process!` on it, `Payola::ChargeChard`
will completely ignore the value that's in the `stripe_token` field. You
just have to set it to something so the validation doesn't fail.

See Payola::CharageCard for details[1].

--Pete

[1]:
https://github.com/peterkeen/payola/blob/master/app/services/payola/charge_card.rb#L24-L33

**Comment by dylanjha** [comment]
This works! Thanks. :clap:
