### ISSUE TITLE
Subscription Help

### ISSUE THREAD

**Issue by stevendelarwelle** [peterkeen/payola#110]
I'm currently using Devise for my users and I'm having a problem getting past when you enter email, cc, expiration...into the checkout button for subscriptions. I look at stripe and i see in the logs that the new subscription was posted, but then my app just sits there with the Please Wait...and nothing else happens.

Here is my controller. I'm fairly new to rails and I dont know if i have this set up correctly. I've also purchased Peter's book and its different setup than payola gem.
````ruby
class SubscriptionsController < ApplicationController
  # bring in the `render_payola_status` helper.
  include Payola::StatusBehavior

  def create
    puts 'create subscription'
    # do any required setup here, including finding or creating the owner object
    owner = create_user(params[:email])    
    #owner = current_user # this is just an example for Devise
    
    # set your plan in the params hash
    params[:plan] = SubscriptionPlan.find_by(id: params[:plan_id])

    # call Payola::CreateSubscription
    subscription = Payola::CreateSubscription.call(params, owner)

    # Render the status json that Payola's javascript expects
    render_payola_status(subscription)
  end


def create_user(email_address)
  puts 'create_user'
    user = User.find_by(email: email_address)

    return user if user.present?

    raw_token, enc_token = Devise.token_generator.generate(
      User, :reset_password_token)
    password = SecureRandom.hex(32)

    user = User.create!(
      email: email_address,
      password: password,
      password_confirmation: password,
      reset_password_token: enc_token,
      reset_password_sent_at: Time.now
      )

    return user, raw_token
  end
end
````

**Comment by dylanjha** [comment]
@stevendelarwelle after payola posts the payment to stripe, then it makes the request to your Rails controller, like you have here.

Look in the javascript console in your web browser for any errors.  Also check the rails server logs to see if a request hit `SubscriptionsController`.

Have you created a route to the `SubscriptionsController#create` action, and is your form action url pointing to that route?

**Comment by stevendelarwelle** [comment]
I talked with Peter and he stated that the subscription button doesn't use
the controller, it only uses the initializer. You can see the updated
subscription docs on git now.
