### ISSUE TITLE
email receipts for subscriptions.

### ISSUE THREAD

**Issue by dylanjha** [peterkeen/payola#112]
I notice that the receipt mailer only works with a sale guid. Is there any plan to enhance this with support for a subscription guid?

**Comment by stevendelarwelle** [comment]
I have it working for subscription, make sure you add payola views for the
mailers.

**Comment by dylanjha** [comment]
@stevendelarwelle is that on a branch? I'm looking on master, and on latest tag 1.3.0.  I only see ReceiptMailer https://github.com/peterkeen/payola/blob/master/app/mailers/payola/receipt_mailer.rb

Which appears to only look for a `Payola::Sale`. Am I missing something? Or is there some other mailer that handles subscription receipts?

**Comment by TrevorHinesley** [comment]
@dylanjha Subscription has_many sales just like products. It works the same, so you can use the same receipt mailer.

**Comment by dylanjha** [comment]
Ah! I see that `Subscription` has_many sales, that makes sense.

However, when I go through the checkout flow (in development mode) and sign up for a plan I see a `Subscription` get created, and in the stripe dashboard I see the charge succeeded/ money was collected, but I don't see a corresponding `Payola::Sale` object in my database.

Am I missing something? I would expect that every time a customer is charged for a `Subscription`, a `Sale` object would get created with a receipt.

**Comment by peterkeen** [comment]
Subscription related Sale records get created in response to webhooks. Do
you have hooks set up in your environment yet?

**Comment by dylanjha** [comment]
Got it. I was doing this locally in a development environment, thus no webhooks.  Thanks.

**Comment by TrevorHinesley** [comment]
Dylan, just FYI you can still use webhooks locally (and should), just
utilize a service like ngrok.com (free and highly recommended) to forward
webhooks to your localhost. Works great.

On Sun, Apr 5, 2015 at 3:09 PM, Dylan Jhaveri <notifications@github.com>
wrote:

> Closed #112 <https://github.com/peterkeen/payola/issues/112>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterkeen/payola/issues/112#event-273719744>.
>



-- 
Trevor Hinesley
c: (334) 790-4500
e: trevor.hinesley@gmail.com
e2: trevor@recruittalk.com

Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, any dissemination, publication
or copying of this e-mail is strictly prohibited. The sender does not
accept any responsibility for any loss, disruption or damage to your data
or computer system that may occur while using data contained in, or
transmitted with, this e-mail.
