### ISSUE TITLE
Payola (subscription) is disabling ALL the buttons

### ISSUE THREAD

**Issue by jipiboily** [peterkeen/payola#113]
It looks like the JS in Payola is disabling the buttons when we submit the form, which makes sense. That said, it is disabling all the buttons, not just the ones from the form, in my case, I have a button in the top menu...this is disabling it.

[See it on video](http://sharing.rainforestqa.com/0k0L090X0d3q).

**Comment by peterkeen** [comment]
Yep, sorry about this. Fixed in 6d8497c, will ship in v1.3.3.
