### ISSUE TITLE
Feature request: admin section

### ISSUE THREAD

**Issue by jipiboily** [peterkeen/payola#114]
This would have/need:
- [ ] change subscription
- [ ] extend a trial
- [ ] give a free month (or any period you use)

Thoughts?

**Comment by peterkeen** [comment]
This is a planned Payola Pro feature.

**Comment by archonic** [comment]
https://github.com/sferik/rails_admin may be a reasonable standin. It would of course need a few custom actions to converse with Stripe to complete changing a plan or handing out a free month. I suspect giving a free month should be done by changing a customer's trial start and trial end dates.
