### ISSUE TITLE
How to have a form for the credit card that is not tied to plans?

### ISSUE THREAD

**Issue by jipiboily** [peterkeen/payola#115]
I would love to be able to have the subscriptions as it is now into two different and independent chunks:
- a form to add a credit card
- a different form to pick up a plan, from a list

Did I miss something? I don't think that's possible/built-in right now? Any plans? Where should I look to in the code to do that if I want to?

Thanks!

**Comment by peterkeen** [comment]
`Payola::CreateSubscription` will create a customer if necessary. Currently there is no way to create a customer and then later associate it with a subscription.

**Comment by jipiboily** [comment]
Thanks for the reply. I guess I'll close this then.
