### ISSUE TITLE
Subscription form post URL issues

### ISSUE THREAD

**Issue by RickCarlino** [peterkeen/payola#125]
hi,

I have the following payment form:

```html
<%= render 'payola/transactions/stripe_header' %>
<%= form_tag("/subscriptions",
      class: 'payola-onestep-subscription-form',
      'data-payola-base-path' => payola_path,
      'data-payola-plan-type' => @plan.plan_class,
      'data-payola-plan-id' => @plan.id
  ) do |f| %>
  <span class="payola-payment-error"></span>
  Email:<br>
  <input type="email" name="stripeEmail" data-payola="email"></input><br>
  Card Number<br>
  <input type="text" data-stripe="number"></input><br>
  Exp Month<br>
  <input type="text" data-stripe="exp_month"></input><br>
  Exp Year<br>
  <input type="text" data-stripe="exp_year"></input><br>
  CVC<br>
  <input type="text" data-stripe="cvc"></input><br>
  <input type="submit"></input>
<% end %>
```

```ruby
class SubscriptionPlan < ActiveRecord::Base
  include Payola::Plan
  belongs_to :subscriber
end
```

I have not setup a route to `/subscriptions`, so obviously it hits a 404 when I try to create a subscription.

 * In the wiki example, is `/subscriptions` defined by the user or by Payola? I noticed that the form expects to know the `payola_path`, so I wasn't sure if the URL was for use by the library or the user.
 * Is `/subscriptions` different than `redirect_path(subscription)`?

**Comment by peterkeen** [comment]
There's an example SubscriptionsController in the wiki. You'd want to map
map `post '/subscriptions' => 'subscriptions#create'`.

**Comment by RickCarlino** [comment]
Thanks for the fast reply!
