### ISSUE TITLE
Can't change plans or cancel account after signing up with the same email

### ISSUE THREAD

**Issue by ThreeWest** [peterkeen/payola#127]
Hi, I'm runing Rails 4.2 and I'm using this app (built with the composer).

I'm getting:
Completed 500 Internal Server Error in 1283ms

Stripe::InvalidRequestError (Customer cus_69I57CUBHgGx3z does not have a subscription with ID sub_69I53Q4VAeansf):

app/controllers/registrations_controller.rb:72:in `cancel_subscription'

The first subscription using the same email address was not removed from the payola subscriptions db table. When I clicked "cancel account" it removed the user from the db but not the subscription. It also didn't delete the customer from stripe. 

 In this case, the Devise user with that email no longer existed so Devise still let me create a new account with that email and Payola created a new subscription for it in the db and on stripe. It appears having two subscriptions with the same email in the db is causing this issue. And the reason why there are two is because when a user cancels their account the subscription doesn't get deleted from the database or Stripe. Double wammy. :)

In the real world, this would happen quite often if a user decides they no longer want the account and cancels it but then decides later to come back (we can only hope). :)

It seems the cancel account feature should remove the user and payola subscription. Or Payola should say no to duplicate emails on subscriptions as well but I'd like both. And it appears having two subscriptions keeps the second account from canceling altogether. Seems like Payola is only dealing with the very first subscription it finds using the user email address and doesn't care if it's active or not.

Also in app/services/payola/cancel_subscription.rb, I changed the code below and it deleted the stripe user and subscription from stripe.com but died in the app and didn't delete the Payola subscription in the db or the user or any of the associated records.

From This:
customer = Stripe::Customer.retrieve(subscription.stripe_customer_id, secret_key)
customer.subscriptions.retrieve(subscription.stripe_id,secret_key).delete({},secret_key)

To This:
customer = Stripe::Customer.retrieve(subscription.stripe_customer_id).delete
customer.subscriptions.retrieve(subscription.stripe_id).delete

**Comment by peterkeen** [comment]
Payola doesn't integrate with Devise at that level. What I would suggest is to use the `payola/subscriptions/cancel` partial to add a cancel button, and then add an event handler to delete the user from the `User` table, if that's what you want to do, something like this:

```ruby
Payola.configure do |config|
  config.subscribe 'payola.subscription.canceled' do |sub|
    owner = sub.owner
    owner.destroy
  end
end
```

The cancel button will redirect to the URL returned by the associated plan's `redirect_url` method. By default this is `/`.

**Comment by ThreeWest** [comment]
Thank you for your reply Peter. However, the issue isn't Devise. The devise user is the only thing that actually gets removed. I would like to see the cancel button actually remove the subscription from the Payola_subscriptions table. That's really the issue I'm reporting on. It's not really an issue with Devise at all. There is no cleanup on the Payola side when someone cancels.

 I'm using the https://github.com/RailsApps/rails-stripe-membership-saas app.  This is the code they have for canceling:

  def cancel_subscription
    subscription = Payola::Subscription.find_by!(owner_id: current_user.id, state: 'active')
    Payola::CancelSubscription.call(subscription)
    subscription.destroy
  end

I need to do more testing and get back to you. I think the confusion is knowing where these two things meet.

**Comment by ThreeWest** [comment]
I changed this:

def cancel_subscription
subscription = Payola::Subscription.find_by!(owner_id: current_user.id, state: 'active')
Payola::CancelSubscription.call(subscription)
end

To this:
  def cancel_subscription
    subscription = Payola::Subscription.find_by!(owner_id: current_user.id, state: 'active')
    Payola::CancelSubscription.call(subscription)
    subscription.destroy
  end

And now the subscription is removed from the Payola subscription table. Will the stripe sync feature of of Payola remove the subscription from stripe after this action?

**Comment by peterkeen** [comment]
The Payola CancelSubscription call will cancel the sub at Stripe. Deleting
subscriptions from Stripe is actually not good practice because it can mess
with your stats.

**Comment by ThreeWest** [comment]
I've left subscription.destroy and this removes the subscription from the db but leaves the description alone in Stripe which as Peter mentioned, is ideal so there is a record.  With the subscription gone from the DB, there should be no issues with having multiple subcriptions with the same email address in the app.
