### ISSUE TITLE
Update Subscription Email when User Updates Account Email

### ISSUE THREAD

**Issue by ThreeWest** [peterkeen/payola#131]
Currently when users update their email address for their account, the email address doesn't get updated on the subscription side. I tried the following code but it doesn't get past the first line. I'm trying to grab the email from the subscription an see if it matches the one on the account.  What should I use to grab the email from the Payola Subscription table?

```ruby
 def change_email
  email = Plan.find_by!(id: params[:user][:email])
  unless email == current_user.email
   if current_user.update_attributes!(email: email)
       subscription = Payola::Subscription.find_by!(owner_id: current_user.id, state: 'active')
       Payola::ChangeSubscriptionPlan.call(subscription, email)
       redirect_to edit_user_registration_path, :notice => "Email changed."
    else
       flash[:alert] = 'Unable to change plan.'
       build_resource
       render :edit
     end
   end
 end
```

**Comment by peterkeen** [comment]
A `Plan` is equivalent to a `Stripe::Plan`, which is a thing that's shared by many users. It has nothing to do with an individual user. To update a customer's email address within Stripe, just update it directly with Stripe, like this:

```ruby
subscription = Payola::Subscription.find_by!(owner: current_user, state: 'active')
secret_key = Payola.secret_key_for_sale(subscription)
customer = Stripe::Customer.retrieve(subscription.stripe_customer_id, secret_key)
customer.email = "the new email address goes here"
customer.save
```

**Comment by ThreeWest** [comment]
*sigh* There needs to be SOME consideration that Payloa has to be somewhat integrated into whatever application that's using it. My question was about updating the email address in the Payola_Subscriptions db table. This doesn't happen and causes issues when cancelling accounts after a user has changed their email address.

 If a user updates their account email address, it should also update the email address of the subscription record in the Payola_Subscriptions table which then should trigger an update to Stripe with the new email address.

**Comment by peterkeen** [comment]
That's what `Payola::Subscription`'s polymorphic `owner` association is for. Put your user object in the owner column then just look it up. You don't need a service object to update the email address in the database tables, you can just update it however you want (`update_attributes` or whatever). If you want that change to propagate back to Stripe you'll have to do it yourself (as of right now).

Could you expand a little bit on what issues differing email address are causing you? You should be using Rails associations (database IDs) and Stripe object IDs to tie things together, not email addresses.
