### ISSUE TITLE
You cannot use a stripe token more than once: tok_........

### ISSUE THREAD

**Issue by Jakedavies** [peterkeen/payola#137]
I am configuring a simple payment button for a subscription plan, I have configured the checkout button to show on the appropriate page and all is well until the stripe credit card form is submitted, after submission the javascript begins polling for the subscription, it returns request 'pending' a few times and then the response is updated to be 'you cannot use a strip token more than once: tok_.....' and the subscription is marked as "errored". I have configured the application according to the simple subscription instructions in the wiki, but am consistently getting this error.

**Comment by peterkeen** [comment]
What do your stripe logs say? Is there a valid subscription within Stripe?

**Comment by Jakedavies** [comment]
Stripe shows the subscription as being submitted fine. I think the problem lies in the event callback from stripe, in my payola init I have the following

```
payola.subscribe 'payola.subscription.active' do |sub| 
    puts sub
    user = User.find_by(email: email_address)
    sub.owner = user
    sub.save!
  end
```

And then when the delayed job worker tries to execute this, I get the response  `undefined variable 'email_address'`, it seemed strange to me to use email address there but the example has nearly exactly that for the subscribe event

**Comment by Jakedavies** [comment]
I have fixed this issue, I am not sure why the wiki says email_address but using sub.email works and makes sense. I thought email_address was a variable injected els ware via ruby magic. 

```
payola.subscribe 'payola.subscription.active' do |sub| 
    user = User.find_by(email: sub.email)
    sub.owner = user
    sub.save!
  end
```

**Comment by peterkeen** [comment]
Great! Could you fix the wiki please?

**Comment by Jakedavies** [comment]
Done

**Comment by preston** [comment]
I may be having a similar issue and am beating my head against a wall. I'm seeing the polling eventually give up and on the server side, my delayed job eventually throwing the following exception. What am I doing wrong here?

	--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper
	job_data:
  	job_class: Payola::Worker::ActiveJob
  	job_id: e908ef89-37c7-4a70-abed-3e1a825eb36c
  	queue_name: default
  	arguments:
  		- Payola::ProcessSubscription
  		- tc1oq8
  	locale: :en
	Last Error
	Toggle full message
	undefined method `stripe_id' for nil:NilClass
	/Users/preston/.rvm/gems/ruby-2.3.1/gems/payola-payments-1.3.0/app/services/payola/start_subscription.rb:24:in `run'
	/Users/preston/.rvm/gems/ruby-2.3.1/gems/payola-payments-1.3.0/app/services/payola/start_subscription.rb:9:in `call'
	/Users/preston/.rvm/gems/ruby-2.3.1/gems/payola-payments-1.3.0/app/models/payola/subscription.rb:132:in `start_subscription'
	/Users/preston/.rvm/gems/ruby-2.3.1/gems/aasm-4.10.1/lib/aasm/core/event.rb:156:in `invoke_callbacks'
	/Users/preston/.rvm/gems/ruby-2.3.1/gems/aasm-4.10.1/lib/aasm/core/event.rb:63:in `fire_callbacks'
	/Users/preston/.rvm/gems/ruby-2.3.1/gems/aasm-4.10.1/lib/aasm/aasm.rb:166:in `aasm_fired'

**Comment by eliotsykes** [comment]
Issue housekeeping - closing.
