### ISSUE TITLE
Pass custom css to stripe checkout button.

### ISSUE THREAD

**Issue by stevendelarwelle** [peterkeen/payola#139]
It would be awesome if we could pass customized css classes to the stripe checkout button.

For instance add a class here
```ruby
<%= render 'payola/subscriptions/checkout', plan: YourSubscriptionPlanClass.first, class: "btn btn-info" %>
```

This would make implementation a breeze, without creating a subscription class. Just a wish list.

**Comment by peterkeen** [comment]
You can tell it what class to apply to the button as well as tweak the styles inline if you like: 

https://github.com/peterkeen/payola/blob/master/app/views/payola/subscriptions/_checkout.html.erb#L2-L3

The defaults match the Stripe Checkout button that `checkout.js` will insert. If you customize the button class you'll typically want to set `button_inner_style` to `''`.
