### ISSUE TITLE
Place link to docs and/or source in the footer of the page

### ISSUE THREAD

**Issue by zspencer** [peterkeen/payola#140]
Hey @peterkeen! We're poking at Payola, and were planning to submit a pull request adding a link to the source and wiki in the footer; but turns out the gh-pages branch isn't payola.io. 

Anyway, adding links to the github repo and the wiki would save about .00015s of time when I'm looking up documentation. So I'm pretty sure it's the most urgent feature request ever ;).

**Comment by peterkeen** [comment]
You mean like this one?

![screenshot 2015-07-01 16 14 41](https://cloud.githubusercontent.com/assets/13977/8463917/5c1c688e-200c-11e5-877b-74fb903bed1c.png)

**Comment by zspencer** [comment]
Not really, as it's not on all the pages.

**Comment by zspencer** [comment]
(and for some reason chrome has decided that it's going to go to the blog instead of the home page if I type "payola" into the "awesome" bar)

**Comment by eliotsykes** [comment]
Closing.
