### ISSUE TITLE
Using Payola with subdomains

### ISSUE THREAD

**Issue by ashwinputhige** [peterkeen/payola#141]
When using Payola in an app with subdomains,

- Is there a way to set subdomain specific Stripe keys? Is there a method that can set the key instead of adding to config file.

Is there any tutorial on using Payola with subdomains?

**Comment by ashwinputhige** [comment]
after some debugging I realised this is not a valid question. Sorry about that.

**Comment by peterkeen** [comment]
There actually is a way to do this. You can put something that responds to `call` in `Payola.publishable_key_retriever` and `Payola.secret_key_retriever`. They both receive either a `Payola::Sale` or `Payola::Subscription` and return their respective key. If you set the owner attribute according to the subdomain, you can send separate keys based on what the owner belongs to. Make sense?

**Comment by ashwinputhige** [comment]
Makes sense.  Thanks. I will try it out and let you know.
