### ISSUE TITLE
Have you considered porting/extending payola to support Chargify?

### ISSUE THREAD

**Issue by oboxodo** [peterkeen/payola#157]
AFAIK Chargify has a pretty similar structure than Stripe, at least for subscriptions, etc, and similar webhooks too.

Are you aware of any efforts similar to Payola but supporting Chargify instead/on top of Stripe?

**Comment by archonic** [comment]
Chargify maintains a ruby API wrapper here:
https://github.com/chargify/chargify_api_ares

**Comment by oboxodo** [comment]
Yeah, I know. But that's not equivalent to Payola. That's more like
https://github.com/stripe/stripe-ruby.

On Mon, Sep 7, 2015 at 7:22 PM, Josh <notifications@github.com> wrote:

> Chargify maintains a ruby API wrapper here:
> https://github.com/chargify/chargify_api_ares
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterkeen/payola/issues/157#issuecomment-138386214>.
>



-- 
Diego Algorta : ob.oxo.do

**Comment by nfm** [comment]
@oboxodo I'm in the process of migrating from Chargify to Stripe at the moment, so I'm fairly familiar with how both platforms handle subscriptions, and I think there's probably too much difference between the two platforms to be able to share much code.

It would be great to see a similar gem created for handling subscriptions and sales using Chargify :smile: But I think that would have to be its own thing.

**Comment by oboxodo** [comment]
Hey @nfm ... could you expand a little bit about your migration from Chargify to Stripe? Did you use Payola? Did you end up with a lot less custom code by using Payola+Stripe vs Chargify? Thanks.

**Comment by nfm** [comment]
@oboxodo sure thing. We did end up using Payola to handle Stripe subscriptions. I think our code to integrate with Chargify was probably 3-4x what we needed to integrate with Stripe via Payola, and the Stripe integration is much tidier. I guess that's partly because the Stripe API itself is cleaner than Chargify's, so there are less weird edge cases to deal with.

**Comment by oboxodo** [comment]
Awesome. Thanks. We've been delaying the move for long. But eventually... :) Deleting a lot of old code, specially when it's related to handling $, is a good thing.
