### ISSUE TITLE
Webhooks not working

### ISSUE THREAD

**Issue by fousa** [peterkeen/payola#158]
Hi,

When I add the following code to my payola initializer, I'm unable to get the subscription when I trigger the method from the stripe 'test webhook' backend.

``` ruby
config.subscribe('charge.succeeded') do |subscription|
  puts subscription
end
```

I use ngork in order expose my local development environment. I can see the stripe logging in my rails logs but no subscription information set in my initializer.

**Comment by peterkeen** [comment]
The test webhook button sends fake data. Before the event hits your handler, Payola/StripeEvent will ask Stripe for the event data, and because it's a fake event Stripe doesn't return anything.

**Comment by fousa** [comment]
Okay, so I made actual changes to the subscription and now everything is received correctly.
