### ISSUE TITLE
Hardcoded url for payola-register-form to POST /users

### ISSUE THREAD

**Issue by ngelx** [peterkeen/payola#163]
Hey, nice job with this gem.

I've recently found a bug when trying to create a free subscription without CC. I've followed the instructions here #145 but the AJAX request is hardcoded to `POST /users` [here](https://github.com/peterkeen/payola/blob/9a8738084ffdb6d09294c994b5701d8b9dd2281b/app/assets/javascripts/payola/subscription_form_register.js#L37) no mater what `url`is set in the `form_tag`.

Thanks
Angel

**Comment by nfm** [comment]
@ngelx this looks like an oversight, I'm sure a PR to let you specify a URL to POST to would be accepted :smile:

**Comment by ngelx** [comment]
:+1:

**Comment by nfm** [comment]
:heart:

**Comment by eliotsykes** [comment]
Closed by #171
