### ISSUE TITLE
Syncing existing stripe customers and subscriptions

### ISSUE THREAD

**Issue by jayztemplier** [peterkeen/payola#166]
Hi,
In the process on improving my website (that already support payments using the Stripe gem), I would like to use Payola.

The only problem that I am having right now is that I can't find out to sync the tables created by payola with the existing subscriptions created from the current version of my website in production.

Example: I see a subscription for customer "A" in Stripe. How do I make it appear on my app (using Payola) as well?

Thanks!

**Comment by jayztemplier** [comment]
@peterkeen ? :)

**Comment by peterkeen** [comment]
There is no built-in functionality for that. A simple rake task that walks over your Stripe account and creates `Payola::Subscription objects` is all you need.

**Comment by jayztemplier** [comment]
So creating Subscriptions in the database won't push new Subscriptions to Stripe :) that was mainly my concern.

Thanks!

**Comment by nfm** [comment]
@jayztemplier if you end up writing a rake task for this, and it's relatively generic, it would be great to have a wiki page that gave an example rake task for how you might do this. Alternatively, if it turns out to be generic enough, maybe we could consider including a rake task for this in the repo.

**Comment by jayztemplier** [comment]
@nfm here is a gist with what I have so far: https://gist.github.com/jayztemplier/8120cf08ee7ae625be6d

@peterkeen I have a few question. Can you tell where you get these params from?
- guid
- stripe_token
- stripe_id (I thought it was the subscription id... but it's nil on the subscription created by Payola)
- affiliate_id,
- coupon,
- signed_custom_fields,
- setup_fee

Thanks!

**Comment by jayztemplier** [comment]
ping :( @peterkeen

**Comment by peterkeen** [comment]
`stripe_id` is the stripe subscription id. I don't know why it would be nil. `guid` is assigned by Payola. The rest can just be blank.

**Comment by marcinbiegun** [comment]
I've updated @jayztemplier gist, it still doesn't copy 100% of the data, but it was enough to use on production env in my case: https://gist.github.com/marcinbiegun/a515d175fb9d3961978266786278986f
