### ISSUE TITLE
Can I submit my payola payment form via jquery/ajax?

### ISSUE THREAD

**Issue by JasonMannon** [peterkeen/payola#187]
I want to submit a 2nd form after a successful response from payola.  But, when I try to submit via jQuery, i'm not getting the params I need.  

```
{"utf8"=>"✓",
 "authenticity_token"=>"tokenz/w+R2g==",
 "stripeEmail"=>"test@test.me",
 "controller"=>"subscriptions",
 "action"=>"create"}
```

But when I don't use jQuery to submit my form, my params look like this:

```
{"utf8"=>"✓",
 "authenticity_token"=>"test+token/cc6JbgU5zotokenKzYc2e1vwojsdmt92he11M1U9w==",
 "subscription_plan"=>{"subscription_plan_ids"=>["1"]},
 "stripeEmail"=>"test@test.com",
 "plan_type"=>"subscription_plan",
 "plan_id"=>"",
 "stripeToken"=>"my_token",
 "coupon"=>"",
 "quantity"=>"",
 "controller"=>"subscriptions",
 "action"=>"create"}
```

**Comment by TrevorHinesley** [comment]
Can we see your javascript? Sounds like you either need to serialize the form and pass it as data (if you're submitting AJAX manually using jQuery's `$.ajax` or similar).

**Comment by JasonMannon** [comment]
```
  $('.payola-onestep-subscription-form').on('submit', function(event) {
    event.preventDefault();
    $.ajax({
        type:"POST",
        url: "/subscriptions",
        data: $('.signup-form').serialize(),
        error:function(data) {
          debugger;
        },
        success:function(data){
            this.unbind('submit').submit();
        }
    });
  });
```

**Comment by JasonMannon** [comment]
I tried to do it with jquery-ujs as well by adding `remote: true` to the form, and got the same params back.
```
  Signup form
  $('.payola-onestep-subscription-form').
    on('ajax:success', function() {
      debugger;
    }).on('ajax:error', function() { debugger; });
```

**Comment by TrevorHinesley** [comment]
Ah I see, you're binding to submit. This won't work because Payola manually
grabs the inputs and appends them to the form, so you'll need to do the
same before submitting, see:
https://github.com/peterkeen/payola/blob/master/app/assets/javascripts/payola/subscription_form_onestep.js
