### ISSUE TITLE
Mounting Payola as a devise authenticated route?

### ISSUE THREAD

**Issue by algodave** [peterkeen/payola#197]
I'm currently mounting Payola engine as a devise authenticated route:

```ruby
# in routes.rb
authenticated :user do
  # ... other routes ... 
  mount Payola::Engine => '/pay', as: :payola
  # ... other routes ...
end
```

this way, `StripeEvent::Engine` too is mounted as an authenticated route, resulting in a 404 returned to Stripe webhook requests. The solution I've come up with so far is simply to add a `mount` line for `StripeEvent::Engine` on my app's `routes.rb` *outside* of the `authenticated` block, and configure such endpoint on Stripe settings rather than the one mounted by Payola.

What do you think about this solution?
As an alternative, would it be safe to mount Payola outside of the `authenticated` block?

**Comment by peterkeen** [comment]
It's generally safe to mount `Payola::Engine` outside of the `authenticated` block as long as you implement the `payola_can_modify_subscription?` method in your `ApplicationController`. This method gets passed a subscription and should return true if the current user can modify the given subscription or false if not.

**Comment by algodave** [comment]
Thank you for the prompt reply. I have the the `payola_can_modify_subscription?` method implemented in my `ApplicationController`. Perhaps the `payola_can_modify_customer?` method is needed too, in order to secure the following endpoint:

```
update_customer POST   /update_customer/:id(.:format)            payola/customers#update
```

PS: I'm using the master branch

**Comment by peterkeen** [comment]
Ah, yes. That's true.

**Comment by algodave** [comment]
About the following endpoints:

```
                     confirm GET    /confirm/:guid(.:format)                  payola/transactions#show
                      status GET    /status/:guid(.:format)                   payola/transactions#status
        confirm_subscription GET    /confirm_subscription/:guid(.:format)     payola/subscriptions#show
         subscription_status GET    /subscription_status/:guid(.:format)      payola/subscriptions#status
```

if an attacker grabs in some way a subscription's guid, would he be able to read those data?

**Comment by peterkeen** [comment]
The status endpoints will mirror back the given GUID and return the
object's `state` and `error` columns, but nothing else about the object.
The `confirm` endpoints will redirect to whatever your application has set
as the `redirect_path` on your plan or sellable, which presumably you
already have authenticated.

**Comment by algodave** [comment]
Thanks for answering! I would close this issue then
