### ISSUE TITLE
Rails 5 / Turbolinks 5 support?

### ISSUE THREAD

**Issue by archonic** [peterkeen/payola#204]
I'm looking forward to all the nifty things Turbolinks 5 offers. Are there any plans to support Turbolinks 5, or to ensure compatibility with Rails 5?

**Comment by eliotsykes** [comment]
Hi @archonic - I intend to have a go at adding Rails 5 support shortly.

**Comment by jordanyeo** [comment]
Would it be as simple as just placing a few:

`data-turbolinks="false"` attributes on some of the partials? Hoping to include turbolinks in my newly upgraded rails5 app, would be awesome if I didn't have to conditionally include it based on specific views and instead the gem supported blocking specific requests where necessary.

**Comment by eliotsykes** [comment]
Some related discussion on Turbolinks support: https://github.com/peterkeen/payola/issues/199

**Comment by eliotsykes** [comment]
Rails 5 support added in #232. Closing this now (for Turbolinks support in Rails 5 discussion continues in #199).
