### ISSUE TITLE
After setting up my Custom Form, I get error: "**Completed 500 (Internal Server Error)**" whenever I click "PAY" for a job post with Payola

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [peterkeen/payola#215]
![error 1](https://cloud.githubusercontent.com/assets/15254043/14750761/616e482a-08be-11e6-9f50-7d0334275eb4.png)

Is there any other thing I need to set to make this work?

**Comment by peterkeen** [comment]
This is very likely not a Payola problem. What do your server logs say?

**Comment by AfolabiOlaoluwa** [comment]
Here is what I have on my Server Development Log:

`Started POST "/payola/buy/job/farflung-f9418cfd37de67f5bd733b3d2ea39188" for 127.0.0.1 at 2016-04-22 19:23:09 +0100
Processing by Payola::TransactionsController#create as */*
  Parameters: {"stripeToken"=>"tok_1838xhCc1zXXaita55mLNRqE", "stripeEmail"=>"mess@gmail.com", "authenticity_token"=>"hxHmJLfGxuI1sjt9/KTrGVm2fNaGvMztqf91dq2Ij/M=", "product_class"=>"job", "permalink"=>"farflung-f9418cfd37de67f5bd733b3d2ea39188"}
  Payola::Affiliate Load (16.0ms)  SELECT  "payola_affiliates".* FROM "payola_affiliates"  WHERE (lower(code) = lower(NULL))  ORDER BY "payola_affiliates"."id" ASC LIMIT 1
  Job Load (0.0ms)  SELECT  "jobs".* FROM "jobs"  WHERE "jobs"."permalink" = 'farflung-f9418cfd37de67f5bd733b3d2ea39188' LIMIT 1
  Payola::Coupon Load (0.0ms)  SELECT  "payola_coupons".* FROM "payola_coupons"  WHERE (lower(code) = lower(NULL))  ORDER BY "payola_coupons"."id" ASC LIMIT 1
   (1.0ms)  begin transaction
  Payola::Sale Exists (1.0ms)  SELECT  1 AS one FROM "payola_sales"  WHERE "payola_sales"."guid" IS NULL LIMIT 1
  CACHE (0.0ms)  SELECT  1 AS one FROM "payola_sales"  WHERE "payola_sales"."guid" IS NULL LIMIT 1
  Payola::Sale Exists (0.0ms)  SELECT  1 AS one FROM "payola_sales"  WHERE "payola_sales"."guid" = 'ikr4pt' LIMIT 1
  SQL (51.0ms)  INSERT INTO "payola_sales" ("amount", "created_at", "currency", "email", "guid", "product_id", "product_type", "state", "stripe_token", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["amount", 20000], ["created_at", "2016-04-22 18:23:10.581964"], ["currency", "usd"], ["email", "mess@gmail.com"], ["guid", "ikr4pt"], ["product_id", 6], ["product_type", "Job"], ["state", "pending"], ["stripe_token", "tok_1838xhCc1zXXaita55mLNRqE"], ["updated_at", "2016-04-22 18:23:10.581964"]]
  SQL (1.0ms)  INSERT INTO "versions" ("created_at", "event", "item_id", "item_type") VALUES (?, ?, ?, ?)  [["created_at", "2016-04-22 18:23:10.581964"], ["event", "create"], ["item_id", 16], ["item_type", "Payola::Sale"]]
   (123.8ms)  commit transaction
Completed 500 Internal Server Error in 1713ms`

**Comment by peterkeen** [comment]
Not enough information to go on, but it looks like it's blowing up after the sale is created since it looks like a successful insert. What happens after that in your controller?

**Comment by AfolabiOlaoluwa** [comment]
Okay, I have posted a detailed information on Stackoverflow.
http://stackoverflow.com/questions/36665363/i-get-error-500-internal-server-error-when-i-try-to-pay-with-payola-stripe-cu

**Comment by peterkeen** [comment]
Your browser console indicates your server is dumping the error as HTML and the JS is trying to parse it as JSON. Could you post the result of that POST (it should be in your network tab)

**Comment by AfolabiOlaoluwa** [comment]
![error2](https://cloud.githubusercontent.com/assets/15254043/14752151/852dc428-08c5-11e6-9fc7-178824b94d12.png)

**Comment by peterkeen** [comment]
Click on the red response and paste the HTML that's getting returned.

**Comment by AfolabiOlaoluwa** [comment]
Okay, here is the HTML returned:

<header>
  <h1>
    RuntimeError
      in Payola::TransactionsController#create
  </h1>
</header>

<div id="container">
  <h2>No eligible background worker systems found.</h2>

  
  
Rails.root: F:/Rails Programs/RubymineProjects/App

Framework Trace
payola-payments (1.4.0) lib/payola/worker.rb:31:in `autofind'
payola-payments (1.4.0) lib/payola.rb:67:in `queue!'
payola-payments (1.4.0) app/controllers/concerns/payola/async_behavior.rb:37:in `create_object'
payola-payments (1.4.0) app/controllers/payola/transactions_controller.rb:18:in `create'
actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
rack (1.5.5) lib/rack/etag.rb:23:in `call'
rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.5) lib/rack/head.rb:11:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.5) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/application.rb:144:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
rack (1.5.5) lib/rack/content_length.rb:14:in `call'
rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

Full Trace
payola-payments (1.4.0) lib/payola/worker.rb:31:in `autofind'
payola-payments (1.4.0) lib/payola.rb:67:in `queue!'
payola-payments (1.4.0) app/controllers/concerns/payola/async_behavior.rb:37:in `create_object'
payola-payments (1.4.0) app/controllers/payola/transactions_controller.rb:18:in `create'
actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
rack (1.5.5) lib/rack/etag.rb:23:in `call'
rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.5) lib/rack/head.rb:11:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.5) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/application.rb:144:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
rack (1.5.5) lib/rack/content_length.rb:14:in `call'
rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'


  
Request parameters
{"stripeToken"=>"tok_1839WTCc1zXXaitazBqbFCs7",
 "stripeEmail"=>"somuchmess@gmail.com",
 "authenticity_token"=>"hxHmJLfGxuI1sjt9/KTrGVm2fNaGvMztqf91dq2Ij/M=",
 "product_class"=>"job",
 "permalink"=>"farflung-f9418cfd37de67f5bd733b3d2ea39188"}

Session dump
_csrf_token: "hxHmJLfGxuI1sjt9/KTrGVm2fNaGvMztqf91dq2Ij/M="
session_id: "fab203266bc750c7b0c922b56282a681"

Env dump
GATEWAY_INTERFACE: "CGI/1.1"
HTTP_ACCEPT: "*/*"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.8"
REMOTE_ADDR: "127.0.0.1"
REMOTE_HOST: "127.0.0.1"
SERVER_NAME: "localhost"
SERVER_PROTOCOL: "HTTP/1.1"

Response headers
None

</div>

**Comment by peterkeen** [comment]
You need to set up a [background worker system](https://github.com/peterkeen/payola/wiki/Configuration-options#background-jobs).

**Comment by AfolabiOlaoluwa** [comment]
Okay sir, but am so sorry it my first time of Payola and as well new to Ruby on Rails. Where do I set the **Background Worker System** in my application?

**Comment by peterkeen** [comment]
Take a look at the page I linked and google some of those names. If you're using Rails 4.2 or higher, look up the documentation for ActiveJob.

**Comment by AfolabiOlaoluwa** [comment]
After trying to as you requested, I get the following error:

Routing Error

Not Found


Rails.root: F:/Rails Programs/RubymineProjects/App

Framework Trace
payola-payments (1.4.0) app/controllers/payola/transactions_controller.rb:30:in `find_product'
payola-payments (1.4.0) app/controllers/payola/transactions_controller.rb:23:in `find_product_and_coupon'

**Comment by AfolabiOlaoluwa** [comment]
My New Error:
<header>
  <h1>
    Redis::CannotConnectError
      in Payola::TransactionsController#create
  </h1>
</header>

<div id="container">
  <h2>Error connecting to Redis on 127.0.0.1:6379 (Redis::TimeoutError)</h2>

  
  
Rails.root: F:/Rails Programs/RubymineProjects/App

Framework Trace
redis (3.3.0) lib/redis/client.rb:345:in `rescue in establish_connection'
redis (3.3.0) lib/redis/client.rb:331:in `establish_connection'
redis (3.3.0) lib/redis/client.rb:101:in `block in connect'
redis (3.3.0) lib/redis/client.rb:293:in `with_reconnect'
redis (3.3.0) lib/redis/client.rb:100:in `connect'
redis (3.3.0) lib/redis/client.rb:364:in `ensure_connected'
redis (3.3.0) lib/redis/client.rb:221:in `block in process'
redis (3.3.0) lib/redis/client.rb:306:in `logging'
redis (3.3.0) lib/redis/client.rb:220:in `process'
redis (3.3.0) lib/redis/client.rb:187:in `call_pipelined'
redis (3.3.0) lib/redis/client.rb:157:in `block in call_pipeline'
redis (3.3.0) lib/redis/client.rb:293:in `with_reconnect'
redis (3.3.0) lib/redis/client.rb:155:in `call_pipeline'
redis (3.3.0) lib/redis.rb:2299:in `block in multi'
redis (3.3.0) lib/redis.rb:58:in `block in synchronize'
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
redis (3.3.0) lib/redis.rb:58:in `synchronize'
redis (3.3.0) lib/redis.rb:2291:in `multi'
sidekiq (4.1.1) lib/sidekiq/client.rb:171:in `block in raw_push'
connection_pool (2.2.0) lib/connection_pool.rb:64:in `block (2 levels) in with'
connection_pool (2.2.0) lib/connection_pool.rb:63:in `handle_interrupt'
connection_pool (2.2.0) lib/connection_pool.rb:63:in `block in with'
connection_pool (2.2.0) lib/connection_pool.rb:60:in `handle_interrupt'
connection_pool (2.2.0) lib/connection_pool.rb:60:in `with'
sidekiq (4.1.1) lib/sidekiq/client.rb:170:in `raw_push'
sidekiq (4.1.1) lib/sidekiq/client.rb:67:in `push'
sidekiq (4.1.1) lib/sidekiq/worker.rb:115:in `client_push'
sidekiq (4.1.1) lib/sidekiq/worker.rb:59:in `perform_async'
payola-payments (1.4.0) lib/payola/worker/sidekiq.rb:16:in `call'
payola-payments (1.4.0) lib/payola.rb:63:in `queue!'
payola-payments (1.4.0) app/controllers/concerns/payola/async_behavior.rb:37:in `create_object'
payola-payments (1.4.0) app/controllers/payola/transactions_controller.rb:18:in `create'


</div>

**Comment by AfolabiOlaoluwa** [comment]
Solved. The problem being that I didn't start my background worker. After starting Background Worker, transactions got successful.
