### ISSUE TITLE
ChangeSubscriptionQuantity and instrument_quantity_changed

### ISSUE THREAD

**Issue by eliotsykes** [peterkeen/payola#235]
`ChangeSubscriptionQuantity` currently calls

```rb
subscription.instrument_plan_changed(old_quantity)
```

Guessing this ought to be calling `instrument_quantity_changed` instead of `instrument_plan_changed`. 

Original commit: https://github.com/peterkeen/payola/commit/b6c3d1d3ccae058d13ef17fa9cb65bd07abb121c (_cc @TrevorHinesley in case you have an opportunity to verify_)

**Comment by peterkeen** [comment]
Yes, that's true.
