### ISSUE TITLE
Update subscriptions with different period

### ISSUE THREAD

**Issue by Alagaesia93** [peterkeen/payola#236]
Hi all,
thanks for this gem, it's awesome. 

I've found something like a little bug, but maybe I'm doing something wrong.
I have a Plan model which includes Payola::Plan. One plan ("free") has period "year", the other 3 have period "month". Every registered user subscribes free plan, and then he can update later.

When an user updates (payola-onestep-subscription-form) his CC info and plan I have this action in my controller: 
```ruby
def create
	@plan = Plan.find(params[:plan_id])
	params[:plan] = @plan
	@subscription = Payola::Subscription.find_by!(owner: current_user)
	Payola::UpdateCard.call(@subscription, params[:stripeToken])
	@subscription = Payola::ChangeSubscriptionPlan.call(@subscription, @plan)
	current_user.update_attributes(plan: @plan)
	render_payola_status(@subscription)
end
```
But Payola::ChangeSubscriptionPlan.call(@subscription, @plan) does not update current_period_start and current_period_end. It is updated on Stripe, but not on Payola::Subscription local table. 

<h1>Stripe</h1>
![schermata 2016-07-21 alle 12 52 11 pm](https://cloud.githubusercontent.com/assets/11704617/17020462/fc3346b6-4f41-11e6-8fc7-cd7df80e7aaa.png)
<h1>rails console</h1>
`
#<Payola::Subscription id: 3, plan_type: "Plan", plan_id: 1, start: nil, status: nil, owner_type: "User", owner_id: 6, stripe_customer_id: "cus_8rMsVakWCKGgTU", cancel_at_period_end: false, current_period_start: "2016-07-21 10:11:04", current_period_end: "2017-07-21 10:11:04", ended_at: nil, trial_start: nil, trial_end: nil, canceled_at: nil, quantity: 1, stripe_id: "sub_8rMsF18zhqvU7X", stripe_token: nil, card_last4: "4242", card_expiration: "2019-12-01", card_type: "Visa", error: nil, state: "active", email: "example6@temp.it", created_at: "2016-07-21 10:11:02", updated_at: "2016-07-21 10:11:45", currency: "eur", amount: 0, guid: "59jvf0", stripe_status: "active", affiliate_id: nil, coupon: nil, signed_custom_fields: nil, customer_address: nil, business_address: nil, setup_fee: nil, tax_percent: nil> 
`

Thanks in advance (I've just started payments, so I'm still having some spaghetti code)

**Comment by eliotsykes** [comment]
Hi @Alagaesia93,

Currently the `current_period_*` dates are kept in sync with Stripe via the `Subscription#sync_with!` method.

`Subscription#sync_with!` is called when stripe sends the customer.subscription.updated event to your app's webhook endpoint (`Payola::SyncSubscription` is called which calls `Subscription#sync_with!` which updates the `subscription.current_period_*` dates).

Check the webhook endpoint is setup and receiving events from Stripe. `rake routes` ought to show the endpoint path as `/payola/events` or similar. Stripe dashboard should allow you to set your app webhook at https://dashboard.stripe.com/account/webhooks

Please share how you get on and I'll try to help further if needed.

**Comment by Alagaesia93** [comment]
IT'S AWESOME!

Thanks a lot! 

For devs who will ever read this and want to try it. I downloaded <a href="https://ngrok.com/">ngrok</a>, run it to my localhost:3000 local server, registered a webhook to https://<ngrok-result>/payola/events and everything works perfectly! 

THANKS @eliotsykes

**Comment by peterkeen** [comment]
Thanks @eliotsykes :+1:
