### ISSUE TITLE
Updating payola_subscription table on cancellation

### ISSUE THREAD

**Issue by nfunwigabga** [peterkeen/payola#237]
I just started looking at the payola gem and having an issue. The gem creates a table called `payola_subscriptions`, which is supposed to record subscription creation, cancellation, card info etc. So far, when I create a new subscription, it is recorded in this table, but when I cancel a subscription, this table does not get updated. My question is: **Is payola gem supposed to update records on this table if actions such as `cancel subscription` are performed**, or I have to implement these manually in my cancel method? Strange thing (for me) is that `Payola::UpdateCard.call` used in the card_update method updates the database with the new credit card number, but `Payola::CancelSubscription.call` does not update the table. Below is the controller code for canceling subscriptions. 
```ruby
# subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  include Payola::StatusBehavior

  def create
    owner = current_user # this is just an example for Devise
    # set your plan in the params hash
    params[:plan] = SubscriptionPlan.find_by(id: params[:plan_id])
    # call Payola::CreateSubscription
    subscription = Payola::CreateSubscription.call(params, owner)
    current_user.subscription_plan_id=params[:plan_id]
    current_user.save
    flash.notice = "Subscription successfully created"
    UserMailer.subscribe_email(current_user).deliver_now
    render_payola_status(subscription)
  end

  def cancel
    if params[:guid].present?
       @subscription = Payola::Subscription.find_by(:guid => params[:guid])
       Payola::CancelSubscription.call(@subscription) if !@subscription.nil?
       current_user.subscription_plan_id=nil
       current_user.save
       UserMailer.unsubscribe_email(current_user).deliver_now
       flash.notice = "Subscription successfully cancelled"
       redirect_to dashboard_path
    end
  end

  def card_update
      @subscription = Payola::Subscription.find_by!(guid: params[:guid])
      Payola::UpdateCard.call(@subscription, params[:stripeToken])
      flash.notice = "Your credit card successfully updated!"
      render_payola_status(@subscription)
  end

end
```

**Comment by peterkeen** [comment]
You have to set up the webhook with Stripe to get cancellations working.

**Comment by nfunwigabga** [comment]
o ok, thanks. I'll try that and give updates.

**Comment by eliotsykes** [comment]
Wondering if the install instructions would benefit from omitting "Optionally" from the Stripe webhook setup? Current text reads:

> Optionally, tell Stripe about your application. Add this as a webhook ...

**Comment by nfunwigabga** [comment]
Great, setting up the webhook worked. @eliotsykes I think you make a great point. Thanks for your help @peterkeen

**Comment by eliotsykes** [comment]
@nfunwigabga Fantastic, please close the issue if you're happy with the resolution.
