### ISSUE TITLE
Rescuing Runtime Errors

### ISSUE THREAD

**Issue by hwhelchel** [peterkeen/payola#247]
`RuntimeError` is a miscellaneous exception in ruby. Therefore could it not be raised for other reasons than a problem with Stripe or Payola billing logic?

I'd like to understand the motivation behind rescuing `RuntimeError`s instead of having an explicit `Payola::Error` class that could be handled by the engine when necessary.

Thanks!

-H

**Comment by eliotsykes** [comment]
Hi @hwhelchel, thanks for raising this. 

For *some* of the `RuntimeError` `rescue`s, Payola is rescuing them from a callable the developer writes and sets as `Payola.charge_verifier`. My guess is that rescuing `RuntimeError` when these custom callables are called gives a more graceful handling of exception situations for the majority of apps, but granted this may cause undesirable consequences from time-to-time.

If there is a specific code snippet from the gem you can choose for us to focus on first here please do as I think that'll help achieve a better outcome to this discussion.

**Comment by hwhelchel** [comment]
Hey @eliotsykes thanks for your thoughts. There are 8 locations in the library where `RunTimeError` is rescued and handled as a Payola specific error case. For example [when charging a card](https://github.com/peterkeen/payola/blob/3a27392550009c632b55daeb778fd6edc681d4ea/app/services/payola/charge_card.rb#L16). 

I looked at the Ruby standard library and the simple example they give in which a `RunTimeError` can be raised is attempting to modify a frozen object--which could be unrelated to Payola.

```ruby
[1, 2, 3].freeze << 4
#=> RuntimeError: can't modify frozen Array
```
This [discussion](https://github.com/redis/redis-rb/issues/114) over at redis-rb is on the same issue for their library and they decided to implement their own `Error` class.

**Comment by eliotsykes** [comment]
I can see benefits here, what I'm unclear of is what the negative consequences would be, if any. Throwing in some code below to aid discussion.

Some possible error classes to introduce:

```rb
# lib/payola.rb
module Payola
  # Base Payola error:
  class Error < StandardError; end

  # Candidate specific errors:
  class StripeDataMissing < Error; end
  class WorkerError < Error; end
end
```

Replace `RuntimeError` rescues with `Payola::Error` rescues. What would this break or impact negatively for existing Payola apps when they upgrade?

```diff
begin
  # Runs the Payola.charge_verifier callable (optionally) specified by
  sale.verify_charge!
  ...  
-rescue Stripe::StripeError, RuntimeError => e
+rescue Stripe::StripeError, Payola::Error => e
  sale.update_attributes(error: e.message)
  sale.fail!
end
```

The 3 places where Payola raises `RuntimeError` at time of writing:

```diff
# app/services/payola/start_subscription.rb:88
- raise "stripeToken required for new customer with paid subscription"
+ raise StripeDataMissing, "Stripe token required for new customer with paid subscription"

# lib/payola/worker.rb:15
- raise "No such worker type: #{symbol}"
+ raise WorkerError, "No such worker type: #{symbol}"

# lib/payola/worker.rb:31
- raise "No eligible background worker systems found."
+ raise WorkerError, "No eligible background worker systems found."
```

**Comment by hwhelchel** [comment]
I like it. Sorry for the delayed response. I was evaluating implementing Payola but have decided to roll my own smaller stripe integration to match my needs. I enjoyed reading through the library and seeing how you all did things.

**Comment by eliotsykes** [comment]
No problem @hwhelchel, thanks for the feedback. If there are further features that could be added to Payola, do feel free to suggest them.

Closing issue for now. Developers reading this please feel free to comment below if you've run into a problem with the way Payola handles exceptions.
