### ISSUE TITLE
Getting "TypeError: api_key must be a string" when receiving webhooks

### ISSUE THREAD

**Issue by MSeneadza** [peterkeen/payola#256]
I just upgraded to the head of master (revision: 2cbecc0e853504c233e633311e375497b6f2bbf3) from (revision: 009f1f4984242ce0fd0c9bd2ff04c24506bb8c15) and noticed this exception showing up in my logs: "TypeError: api_key must be a string".  [So I also jumped from stripe (1.20.1) to stripe (1.54.0)]That was coming from POST requests to POST https://my-site.com/payola/events.

Has anybody else been getting this?

**Comment by eliotsykes** [comment]
Hi @MSeneadza 

- It sounds like the Stripe API key is not set for at least one request to the Stripe API
- Could you include the full stack trace with line number(s) where this is originating from?

**Comment by MSeneadza** [comment]
@eliotsykes here's the stack trace - https://gist.github.com/MSeneadza/505f1d8cce5ac81c930de5a5410d4543

Thanks

**Comment by peterkeen** [comment]
Looks like Stripe added a check to ensure it is actually a string. We are
using a thing that looks like a String but reads the ENV each time it's
accessed.

Hm. Guess we have to reevaluate that.

**Comment by eliotsykes** [comment]
Possible solutions so far:

**1)** Write `EnvWrapper#is_a?(klass)` to delegate to `ENV[@key].is_a?(klass)` to keep this check in stripe-ruby happy:

```rb
def self.check_api_key!(key)
  raise TypeError.new("api_key must be a string") unless key.is_a?(String)
  key
end
```
Source: https://github.com/stripe/stripe-ruby/blob/3b595a9e7fdf6f6335a71b62ca3d14228d26dabd/lib/stripe/util.rb#L197


**2)** Replace `EnvWrapper` with `ENV['...']` calls in `Payola.reset!`. I'm unclear if this would break anything or possibly cause upgraders issues. Relevant commit where `EnvWrapper` was introduced: https://github.com/peterkeen/payola/commit/828403160278f07a5e5b7fe16d0230cc6673f775

**Comment by peterkeen** [comment]
I don't like either one. Faking is_a? feels kinda gross but also pragmatic. Removing EnvWrapper would make some stuff more complicated. 

Maybe we could send a PR to Stripe to add a call to to_s within the check_api_key! method, but then we have to still deal with the check for versions prior to the one that has our fix.

I guess if I were to pick I would say the is_a? fake is the way to go.

**Comment by eliotsykes** [comment]
Adding for further context and to remind myself: `EnvWrapper` is used to lazily load the env vars and so avoid issues with gem load order and management of env vars via Figaro/Dotenv: See https://github.com/peterkeen/payola/commit/e739e167

**Comment by eliotsykes** [comment]
> I guess if I were to pick I would say the is_a? fake is the way to go.

Agreed

**Comment by eliotsykes** [comment]
Related but not quite the same. I'm getting `TypeError: api_key must be a string` errors when running the Payola specs with a certain combination of gem versions.

Certain versions of stripe-ruby-mock seem to be the trigger (e.g. 2.1.0) used in combination with more recent stripe-ruby versions (e.g. 1.55.0) that perform the api_key must be a String check. 

Upgrading stripe-ruby-mock to 2.3.1 removes the error when running the specs. Will open a PR shortly to enforce this in the gemspec.

**Comment by eliotsykes** [comment]
#261 is slightly related, but does not fix this issue.
