### ISSUE TITLE
Listening for webhooks

### ISSUE THREAD

**Issue by k2xl** [peterkeen/payola#258]
This doesn't seem to be responding to subscription update events (added to payola.rb)
```

Payola.subscribe('customer.subscription.updated') do |sub|
    puts "SUBSCRIPTION UPDATE"
end
```

Am I missing something?

**Comment by eliotsykes** [comment]
Hi @k2xl - check the following and please let us know how you resolve it:

- Stripe dashboard setup to send events to your app's Stripe webhooks URL ending `/payola/events`
- Webhooks URL is visible to public internet
- Restart server after making changes to `config/initializers/payola.rb`
- Stop Spring application preloader after making changes to `config/initializers/payola.rb` with `bin/spring stop` to ensure changes are picked up
- Check `logs/development.log` for the `"SUBSCRIPTION UPDATE"` message

**Comment by eliotsykes** [comment]
Closing after 7 days with no feedback. @k2xl please comment/reopen if there's anything to add in the future.

**Comment by Malstrom** [comment]
i have same problem with:
    config.subscribe 'invoice.created' do |event|
      sub = Payola::Subscription.find_by(stripe_id: event.data.object.subscription)

      User.last.update_attribute :city, 'invoice.created'
    end

Payola saves in db event in table payola_stripe_webhooks but not trigger when this. I try what @eliotsykes writes above but still not working.
