### ISSUE TITLE
Coupons not getting passed through to Checkout.js

### ISSUE THREAD

**Issue by k2xl** [peterkeen/payola#260]
`render 'payola/subscriptions/checkout', coupon: (params[:coupon] rescue ""), description:  ...`

Doesn't seem to pass the coupon through to the checkout.js popup

**Comment by eliotsykes** [comment]
```rb
render 'payola/subscriptions/checkout', coupon: (params[:coupon] rescue ""), description: ...
```

Does `params[:coupon]` have a value? The `rescue ""` looks like its suppressing an error and return an empty coupon.

Does this work?

```
render 'payola/subscriptions/checkout', coupon: 'A-TEST-COUPON', description: ...
```

**Comment by k2xl** [comment]
No :-(

**Comment by eliotsykes** [comment]
Hi @k2xl - if you'd like further help with this please provide any information you think may be relevant. In particular the contents of the template(s) you're using this in would be helpful, along with the HTML output from the page as reported by the browser dev tools.

**Comment by eliotsykes** [comment]
Closing, please reopen if there's anything to add.
