### ISSUE TITLE
New gem version?

### ISSUE THREAD

**Issue by peterkeen** [peterkeen/payola#264]
@eliotsykes what would you say to cutting a new version? Or do you want to finish #254 first?

**Comment by eliotsykes** [comment]
I'd like to leave #254 out until I've tested it out manually and maybe introduce some feature specs using a JS-aware Capybara driver.

New gem version sounds ace 👍  though should we fix this first? Might be a show-stopper for new installs? https://github.com/peterkeen/payola/issues/256

**Comment by peterkeen** [comment]
Yeah, #256 is a good thing to fix first.

**Comment by eliotsykes** [comment]
Any thoughts on version number?

**Comment by the-architect** [comment]
Hey guys. So it seems like #256 is fixed. Do you have time for a new release?

**Comment by peterkeen** [comment]
Tagged v1.5.0.
