### ISSUE TITLE
Where to put Stripe keys?

### ISSUE THREAD

**Issue by johncjensen** [peterkeen/payola#4]
I've tried setting up an initializer/stripe.rb containing the following

``` ruby
Rails.configuration.stripe = {
  :publishable_key => ENV['PUBLISHABLE_KEY'],
  :secret_key      => ENV['SECRET_KEY']
}

Stripe.api_key = Rails.configuration.stripe[:secret_key]
```

I've put test keys into figaro's application.yml, rebooted and still get the js alert of "Stripe Checkout is missing the required 'key'".

Viewing the page source shows the following missing the key within "publishable_key: """

``` html
<script type="text/javascript">
  Payola.setUpStripeCheckoutButton({
    form_id: "payola-button-product-shirt-form",
    button_id: "payola-button-product-shirt",
    error_div_id: "payola-button-product-shirt-errors",
    product_class: "product",
    product_permalink: "shirt",
    price: 10,
    name: "awesome t-shirt",
    description: "awesome t-shirt ($0.10)",
    product_image_path: "",
    publishable_key: "",
    panel_label: "",
    allow_remember_me: true,
    email: "",
    verify_zip_code: false
  });
</script>
```

Where do you place the stripe keys when using Payola? w/out buying the book you link to...

**Comment by jipiboily** [comment]
BTW, this is still not documented :)

**Comment by peterkeen** [comment]
It's on the wiki:
https://github.com/peterkeen/payola/wiki/Configuration-options#stripe-keys

**Comment by jipiboily** [comment]
oops, my bad! Sorry about that. :confused:

**Comment by peterkeen** [comment]
No worries :) It could probably be in a better spot, or maybe linked to in
more spots. If you want to take a stab at either a PR or wiki edits, be my
guest.

**Comment by jipiboily** [comment]
@peterkeen I'm either not following the right path or there are some rough edges, taking notes of that and will either edit the wiki or create a PR. FYI, I want to use Payola for subscriptions.

**Comment by peterkeen** [comment]
Great! Let me know how I can help.
