### ISSUE TITLE
release for 1.2.5?

### ISSUE THREAD

**Issue by jagthedrummer** [peterkeen/payola#80]
Hey Pete, sorry to bug you with this, but I was wondering if you could release 1.2.5 sometime soon so I can get the updated subscription creation handling deployed.  Thanks!

**Comment by peterkeen** [comment]
Done. Sorry about the delay.

**Comment by jagthedrummer** [comment]
Thanks! Would also be nice to get this into prod when you have a chance : https://github.com/peterkeen/payola/pull/84
