### ISSUE TITLE
Conditional logic issue?

### ISSUE THREAD

**Issue by MarkMurphy** [peterkeen/payola#82]
Please correct me if I'm mistaken but wouldn't this create a new customer if the owner in question has exactly 1 subscription?

https://github.com/peterkeen/payola/blob/master/app/services/payola/start_subscription.rb#L58

**Comment by MarkMurphy** [comment]
n/m, I see now that the new subscription is saved first so in the case where the user has already had a subscription and a customer created for them before, this makes sense.

**Comment by peterkeen** [comment]
It will indeed! Good catch.

**Comment by peterkeen** [comment]
Ah, right. This is the code that handles the async part of the subscription
process.

**Comment by MarkMurphy** [comment]
Might be worth adding a comment or changing the logic in that area to be more foolproof. In other words, update it so it doesn't depend on the new subscription object being saved before the find_or_create_customer method is called.

**Comment by peterkeen** [comment]
`StartSubscription` is called by the `process` state change in the
subscription object itself, which only happens in the context of the
`ProcessSubscription` service, which consumes the guid. The reason why
there's a `save!` there is to change the `updated_at` (and thus the paper
trail) to ensure we save off the processing start time. It's a sanity check
thing.

**Comment by MarkMurphy** [comment]
Gotcha.

> The reason why
> there's a `save!` there is to change the `updated_at` (and thus the paper
> trail) to ensure we save off the processing start time. It's a sanity check
> thing.
