### ISSUE TITLE
Coupon code getting lost

### ISSUE THREAD

**Issue by abrambailey** [peterkeen/payola#85]
Gemfile: `gem 'payola-payments', git: 'https://github.com/peterkeen/payola'`

I'm using the following form:
```
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <div class="well">
    <%= form_tag("/subscribe/#{@plan.id}",
      role: 'form',
      class: 'payola-onestep-subscription-form',
      'data-payola-base-path' => '/payola',
      'data-payola-error-selector' => '.payola-error',
      'data-payola-plan-type' => @plan.plan_class,
      'data-payola-plan-id' => @plan.id) do %>
      <div class="form-group">
        <label>Email Address</label>
        <input type="email"
               name="email"
               data-payola="email"
               placeholder="you@example.com"
               class="form-control"
               value="<%= current_user.email %>"
               readonly></input>
      </div>
      <div class="form-group">
        <label>Card number</label>
        <input type="text"
               size="20"
               data-stripe="number"
               class="card-number form-control"
               placeholder="**** **** **** ****"></input>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Exp</label>
            <input type="text"
                   size="8"
                   class="exp-date form-control"
                   placeholder="MM / YY"></input>
            <input type="hidden" data-stripe="exp_month"></input>
            <input type="hidden" data-stripe="exp_year"></input>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>CVC</label>
            <input type="text"
                   size="4"
                   data-stripe="cvc"
                   class="form-control"
                   placeholder="***"></input>
          </div>
        </div>
      </div>

            <div class="form-group">
            <label>Promo Code</label>
            <input type="text"
                   name="coupon"
                   size="20"
                   data-stripe="coupon"
                   class="form-control"
                   placeholder="code"></input>
            </div>

      <div class="text-center">
        <input type="submit" value="Subscribe" class="btn btn-info btn-lg btn-block"></input>
      </div>
      <% end %>
    </div>
  </div>
</div>
```
Here is the form before submit:
![Image of Form](http://i.imgur.com/LqtVwX1.png)

Here is what I'm seeing in my log:
```
Processing by SubscribeController#create as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"dIaCPWDJaBq0m/rqxiFSfLLNILcLtdhaQ4D6nAYLe3p6bbX2d/O6DPQ1BEo0T3+9VY431IbaI1sDdpRN3quLDQ==", "email"=>"test@test.com", "coupon"=>"", "plan_type"=>"subscription_plan", "plan_id"=>"4", "stripeToken"=>"tok_15Oh9BIxHSxj5NYxOOjpClL0", "stripeEmail"=>"abram@hearingtracker.com", "quantity"=>"", "id"=>"4"}
```

**Comment by peterkeen** [comment]
Instead of `data-stripe="coupon"`, use `data-payola="coupon"`. You can see the javascript that picks that up here: https://github.com/peterkeen/payola/blob/master/app/assets/javascripts/payola/subscription_form_onestep.js#L22

**Comment by funkdified** [comment]
Thanks Peter. I actually looked at that file and still missed the difference. I kept checking my spelling of coupon!

**Comment by funkdified** [comment]
I think I may have run into a bug.. Whenever I enter a coupon code that
doesn't exist on the Stripe dashboard, I just see my server repeatedly
calling /subscription_status/id

Like this:

Started GET "/payola/subscription_status/avk0ln" for 127.0.0.1 at
2015-02-26 20:42:47 -0600
Processing by Payola::SubscriptionsController#status as */*
  Parameters: {"guid"=>"avk0ln"}
  User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 7
 ORDER BY `users`.`id` ASC LIMIT 1
  Payola::Affiliate Load (0.2ms)  SELECT  `payola_affiliates`.* FROM
`payola_affiliates` WHERE (lower(code) = lower(NULL))  ORDER BY
`payola_affiliates`.`id` ASC LIMIT 1
  Payola::Subscription Load (0.2ms)  SELECT  `payola_subscriptions`.* FROM
`payola_subscriptions` WHERE `payola_subscriptions`.`guid` = 'avk0ln' LIMIT
1
Completed 400 Bad Request in 16ms (Views: 0.4ms | ActiveRecord: 0.6ms |
Solr: 0.0ms)

Started GET "/payola/subscription_status/avk0ln" for 127.0.0.1 at
2015-02-26 20:42:47 -0600
Processing by Payola::SubscriptionsController#status as */*
  Parameters: {"guid"=>"avk0ln"}
  User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 7
 ORDER BY `users`.`id` ASC LIMIT 1
  Payola::Affiliate Load (0.2ms)  SELECT  `payola_affiliates`.* FROM
`payola_affiliates` WHERE (lower(code) = lower(NULL))  ORDER BY
`payola_affiliates`.`id` ASC LIMIT 1
  Payola::Subscription Load (0.2ms)  SELECT  `payola_subscriptions`.* FROM
`payola_subscriptions` WHERE `payola_subscriptions`.`guid` = 'avk0ln' LIMIT
1
Completed 400 Bad Request in 16ms (Views: 0.4ms | ActiveRecord: 0.6ms |
Solr: 0.0ms)

Is there a solution to this, or am I doing something wrong?

Thanks,
Abram

**Comment by funkdified** [comment]
Pete, It's been a couple weeks, and I thought I'd just check to see if you'd had a look at this comment? Shall I post as a new issue?

**Comment by funkdified** [comment]
After lots of testing with stripe Test Mode, I finally flipped the switch by adding my live keys and creating some subscription plans in Live Mode (via the rails production console). The subscription plans were added, and I put in my real CC details to test the system. Unfortunately, I am experiencing the repeated hits to `/subscription_status/id`, just like in my coupon issue above. Here is the server output:
```
Completed 200 OK in 774ms (Views: 0.5ms | ActiveRecord: 229.3ms | Solr: 0.0ms)
Started GET "/payola/subscription_status/dfgcep" for 70.112.251.173 at 2015-03-17 23:35:09 +0000
Processing by Payola::SubscriptionsController#status as */*
  Parameters: {"guid"=>"dfgcep"}
Completed 400 Bad Request in 13ms (Views: 0.3ms | ActiveRecord: 6.7ms | Solr: 0.0ms)
Started GET "/payola/subscription_status/dfgcep" for 70.112.251.173 at 2015-03-17 23:35:10 +0000
Processing by Payola::SubscriptionsController#status as */*
  Parameters: {"guid"=>"dfgcep"}
Completed 400 Bad Request in 14ms (Views: 0.4ms | ActiveRecord: 7.7ms | Solr: 0.0ms)
Started GET "/payola/subscription_status/dfgcep" for 70.112.251.173 at 2015-03-17 23:35:10 +0000
Processing by Payola::SubscriptionsController#status as */*
  Parameters: {"guid"=>"dfgcep"}
Completed 400 Bad Request in 16ms (Views: 0.3ms | ActiveRecord: 10.0ms | Solr: 0.0ms)
Started GET "/hearing-providers/33-don-kim" for 199.21.99.207 at 2015-03-17 23:35:11 +0000
Processing by DispensersController#show as */*
```  

Any help would be appreciated. Thanks Pete!

**Comment by eliotsykes** [comment]
Issue house-cleaning. Please report new issue if the coupon code problem reappears.
