### ISSUE TITLE
Payment Details - Description

### ISSUE THREAD

**Issue by hellojere** [peterkeen/payola#88]
I must be just not seeing this in the documentation, but can't find anywhere how to set the description that appears in the Stripe Invoice itself. Currently it's a short random string, but would definitely need to have the invoice name there for production use. 

I know it's updatable from the Stripe website, but that's not ideal at all. Could someone kindly point this out to me, please?

**Comment by peterkeen** [comment]
You can provide a callable to Payola named `additional_charge_attributes`, like this:

```ruby
Payola.configure do |config|
  config.additional_charge_attributes = lambda do |sale, customer|
    # sale is a Payola::Sale
    # customer is a Stripe::Customer
    { description: "My what a lovely card you have" }
  end
end
```

The hash you return will get merged with the defaults, which are:

```ruby
amount: sale.amount,
currency: sale.currency,
customer: customer.id,
description: sale.guid,
```

Note that currently this only applies to one-time charges.

**Comment by nathanbertram** [comment]
Thanks!
