### ISSUE TITLE
Support API version 2015-02-18

### ISSUE THREAD

**Issue by peterkeen** [peterkeen/payola#93]
https://stripe.com/docs/upgrades

`card` and `default_card` are gone, replaced by `source` and `default_source`.

We should probably add a way to peg an API version. That way we don't have to worry about this kind of thing immediately.

**Comment by jwo** [comment]
For anyone coming after me, I got around this by pegging stripe api version by adding to my config/initializers/payola.rb. It's the last version before their breaking changes on 2015-02-18.

`Stripe.api_version = "2015-02-16"`
