### ISSUE TITLE
Subscriptions broken w/latest Stripe gem

### ISSUE THREAD

**Issue by peburrows** [peterkeen/payola#96]
When using Payola with the latest version of the stripe gem (`1.20.1`), the `StartSubscription.run` method throws the following exception:

`NoMethodError: undefined method 'cards' for #<Stripe::Customer:...>`

The offending code is on [line 30 of the `StartSubscription` class](https://github.com/peterkeen/payola/blob/master/app/services/payola/start_subscription.rb#L30).

It seems at some point Stripe removed the `Stripe::Customer#cards` method and replaced it with `Stripe::Customer::#sources`. Changing the offending line to call the `#sources` method instead seems to fix things for me for me, but I haven't had a chance to run the full test suite to ensure that it doesn't break something else.

**Comment by peterkeen** [comment]
You can fix this (temporarily) with by adding this code in your payola initializer:

```
Stripe.api_version = "2015-02-16"
```

See #93 for details on why this is happening.
